#!/usr/bin/env bash

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Interactive wizard:
#  1. Collect substrate test-cluster env values.
#  2. Generate scratch/ate-dev-env.sh.
#  3. Build & push the orchestrator image (hardcoded to live under
#     ${KO_DOCKER_REPO}/substrate-benchmark-orchestrator:latest).
#  4. Render scratch/cronjob.yaml with the orchestrator image baked in.
#
# Re-running this script is safe; scratch/ is overwritten.
#
# TODO: drive workload-cluster creation and IAM/Workload Identity bindings
# from tools/setup-gcp (see tools/setup-gcp/cmd/cluster.go) instead of leaving
# them as manual gcloud steps in README.md. That tool already encodes the
# required beta APIs, Workload Identity pool, and node config; this wizard
# should call it (or its equivalent in tools/setup-gcp) once we know the
# values collected below.

set -o errexit -o nounset -o pipefail

ROOT="$(git rev-parse --show-toplevel)"
AUTOMATION_DIR="${ROOT}/benchmarking/automation"
SCRATCH_DIR="${AUTOMATION_DIR}/scratch"

prompt() {
  local var_name="$1"
  local description="$2"
  local default="${3:-}"
  local value=""
  if [[ -n "${default}" ]]; then
    read -r -p "${description} [${default}]: " value
    value="${value:-${default}}"
  else
    while [[ -z "${value}" ]]; do
      read -r -p "${description}: " value
    done
  fi
  printf -v "${var_name}" '%s' "${value}"
}

echo "=== Substrate benchmark orchestrator setup ==="
echo

prompt PROJECT_ID "GCP project ID for the test cluster"
prompt GCE_REGION "GCE region" "us-central1"
prompt CLUSTER_LOCATION "Test cluster location (zone or region)" "us-central1-c"
prompt CLUSTER_NAME "Test cluster name" "substrate-poc"
prompt KO_DOCKER_REPO "Artifact registry path for built images" "gcr.io/${PROJECT_ID}/ate-images"
prompt BUCKET_NAME "GCS snapshot bucket name" "snapshot-substrate-test-${PROJECT_ID}"

IMAGE_TAG="$(git -C "${ROOT}" rev-parse --short HEAD)"
if ! git -C "${ROOT}" diff --quiet HEAD -- benchmarking/automation; then
  IMAGE_TAG="${IMAGE_TAG}-dirty"
fi
ORCHESTRATOR_IMAGE="${KO_DOCKER_REPO}/substrate-benchmark-orchestrator:${IMAGE_TAG}"

echo
echo "Will build orchestrator image: ${ORCHESTRATOR_IMAGE}"
echo

mkdir -p "${SCRATCH_DIR}"

cat > "${SCRATCH_DIR}/ate-dev-env.sh" <<EOF
# Generated by benchmarking/automation/setup.sh.
# Baked into the orchestrator image; sourced at runtime by orchestrator.py
# and by hack/install-ate.sh / benchmarking/workloads/deploy.sh.

export PROJECT_ID=${PROJECT_ID}
export PROJECT_NUMBER=\$(gcloud projects describe \${PROJECT_ID} --format="value(projectNumber)")

export GCE_REGION=${GCE_REGION}
export CLUSTER_LOCATION=${CLUSTER_LOCATION}

export CLUSTER_NAME=${CLUSTER_NAME}

export BUCKET_NAME=${BUCKET_NAME}

export KO_DOCKER_REPO=${KO_DOCKER_REPO}
export KO_DEFAULTPLATFORMS=linux/amd64
EOF

echo "Wrote ${SCRATCH_DIR}/ate-dev-env.sh"

echo
echo "Building ${ORCHESTRATOR_IMAGE}..."
docker build -t "${ORCHESTRATOR_IMAGE}" "${AUTOMATION_DIR}"
echo "Pushing ${ORCHESTRATOR_IMAGE}..."
docker push "${ORCHESTRATOR_IMAGE}"

ORCHESTRATOR_IMAGE="${ORCHESTRATOR_IMAGE}" \
  envsubst '${ORCHESTRATOR_IMAGE}' \
  < "${AUTOMATION_DIR}/manifests/cronjob.yaml.tmpl" \
  > "${SCRATCH_DIR}/cronjob.yaml"

# Append a ConfigMap with the current tests.yaml; the orchestrator pod
# mounts it at /etc/orchestrator/tests.yaml. Editing tests.yaml + re-applying
# this file is enough to change the test list — no image rebuild needed.
echo "---" >> "${SCRATCH_DIR}/cronjob.yaml"
kubectl create configmap substrate-benchmark-tests \
    --namespace=substrate-benchmark \
    --from-file=tests.yaml="${AUTOMATION_DIR}/tests.yaml" \
    --dry-run=client -o yaml \
    >> "${SCRATCH_DIR}/cronjob.yaml"

echo "Wrote ${SCRATCH_DIR}/cronjob.yaml"
echo
echo "=== Next steps ==="
echo "1. Edit ${SCRATCH_DIR}/cronjob.yaml and fill in the --repo / --branch / --dest args."
echo "2. Apply to the orchestration cluster:"
echo "     kubectl --context=<orchestration-cluster> apply -f ${SCRATCH_DIR}/cronjob.yaml"
echo
echo "To update the test list later without rebuilding the orchestrator:"
echo "  kubectl --context=<orchestration-cluster> -n substrate-benchmark \\"
echo "    create configmap substrate-benchmark-tests \\"
echo "    --from-file=tests.yaml=${AUTOMATION_DIR}/tests.yaml \\"
echo "    --dry-run=client -o yaml | kubectl apply -f -"
